// ⚠️ THIS ORDER IS LOAD-BEARING — do not "tidy" tokens.css back to the top.
//
// base.css and composition.css both define framework DEFAULTS on :root, and
// the theme redefines a subset of them on :root too. Same selector, same
// specificity, so the winner is whichever is bundled LAST. tokens.css must
// therefore come after every file that ships defaults, or the theme silently
// loses — which is exactly what happened while it was imported second: all 24
// themes had their --stage-pad-*, --dur-*, --ease-*, --hero-num-*, --r-card,
// --rule-w/-style and --shadow-stage overridden right back to base.css's
// values. paper-press asks for 140px stage padding and was rendering at 96.
//
// Load defaults first, then let the theme win:
import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/base.css"; // primitives + default token values
import "./styles/composition.css"; // 8 compositions + visual roles + density tokens (VISUAL-DIRECTION.md)
import "./styles/evidence.css"; // paper-mode evidence layer (PAPER-INTERPRETATION.md §3)
import "./styles/tokens.css"; // ACTIVE THEME — generated by scaffold, must stay last (see THEMES.md)
import "./styles/animations.css";

import { useCallback, useEffect } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { LayoutDebug } from "./components/LayoutDebug";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  // ── ?layout=1 mode: visual QA overlay (see references/VISUAL-QA.md §3) ──
  const layoutDebugOn =
    typeof window !== "undefined" &&
    new URLSearchParams(window.location.search).get("layout") === "1";

  // Expose the current cursor to the LayoutDebug readout (read-only window
  // hook). Chapter and step stay separate fields — the readout prints both,
  // and a packed number would just have to be decoded again on the other side.
  useEffect(() => {
    type Cursor = { chapter: number; step: number };
    const w = window as unknown as { __presentationCursor?: () => Cursor };
    w.__presentationCursor = () => ({
      chapter: stepper.cursor.chapter,
      step: stepper.cursor.step,
    });
    return () => {
      delete w.__presentationCursor;
    };
  }, [stepper.cursor.chapter, stepper.cursor.step]);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className="scene">
          <Cmp step={stepper.cursor.step} />
        </div>
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
      {layoutDebugOn && <LayoutDebug />}
    </>
  );
}
