// ⚠️ THIS ORDER IS LOAD-BEARING — do not "tidy" tokens.css back to the top.
//
// base.css and composition.css both define framework DEFAULTS on :root, and
// the theme redefines a subset of them on :root too. Same selector, same
// specificity, so the winner is whichever is bundled LAST. tokens.css must
// therefore come after every file that ships defaults, or the theme silently
// loses — which is exactly what happened while it was imported second: all 24
// themes had their --stage-pad-*, --dur-*, --ease-*, --hero-num-*, --r-card,
// --rule-w/-style and --shadow-stage overridden right back to base.css's
// values. paper-press asks for 140px stage padding and was rendering at 96.
//
// Load defaults first, then let the theme win:
import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/base.css"; // primitives + default token values
import "./styles/composition.css"; // 8 compositions + visual roles + density tokens (VISUAL-DIRECTION.md)
import "./styles/evidence.css"; // paper-mode evidence layer (PAPER-INTERPRETATION.md §3)
import "./styles/paper-figure.css"; // paper-mode original figures (PAPER-INTERPRETATION.md §6)
import "./styles/figure-lens.css"; // spotlight / zoom / crop on original figures (§6.1.1)
import "./styles/scene.css"; // scene component layer (components/scene/*)
import "./styles/end-credits.css"; // end credits after the last step (components/EndCredits)
import "./styles/tokens.css"; // ACTIVE THEME — generated by scaffold, must stay last (see THEMES.md)
import "./styles/animations.css";

import { useCallback, useEffect, useState } from "react";
import type React from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { EndCredits, type Credits } from "./components/EndCredits";
import { LayoutDebug } from "./components/LayoutDebug";
import { PausedIndicator } from "./components/PausedIndicator";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { usePlaybackRate } from "./hooks/usePlaybackRate";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";
import creditsData from "./credits.json";

const CREDITS = creditsData as Credits;

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";

  // 片尾：最后一章最后一步之后再「下一步」进入，不是章节、不占步数（见 components/EndCredits）
  const [ended, setEnded] = useState(false);
  const atEnd =
    stepper.cursor.chapter === CHAPTERS.length - 1 &&
    stepper.cursor.step === ch.narrations.length - 1;
  // 光标一动（进度条跳章、Home、数字键）就离开片尾
  useEffect(() => {
    setEnded(false);
  }, [stepper.cursor.chapter, stepper.cursor.step]);
  // 键盘：在 window 捕获阶段先拦，末步的「下一步」进片尾；片尾里的「上一步」只退出片尾，
  // 不让 useStepper 再跟着退一步
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement) return;
      const fwd = e.key === "ArrowRight" || e.key === " ";
      const back = e.key === "ArrowLeft" || e.key === "Backspace";
      if (ended && (fwd || back)) {
        e.preventDefault();
        e.stopPropagation();
        if (back) setEnded(false);
      } else if (!ended && atEnd && fwd) {
        e.preventDefault();
        e.stopPropagation();
        setEnded(true);
      }
    };
    window.addEventListener("keydown", onKey, true);
    return () => window.removeEventListener("keydown", onKey, true);
  }, [ended, atEnd]);

  const { mode, cycleMode, autoStarted, setAutoStarted, paused, togglePause } =
    useAutoMode();
  const { rate, setRate } = usePlaybackRate();

  // ── ?layout=1 mode: visual QA overlay (see references/VISUAL-QA.md §3) ──
  const layoutDebugOn =
    typeof window !== "undefined" &&
    new URLSearchParams(window.location.search).get("layout") === "1";

  // Expose the current cursor to the LayoutDebug readout (read-only window
  // hook). Chapter and step stay separate fields — the readout prints both,
  // and a packed number would just have to be decoded again on the other side.
  useEffect(() => {
    type Cursor = { chapter: number; step: number };
    const w = window as unknown as { __presentationCursor?: () => Cursor };
    w.__presentationCursor = () => ({
      chapter: stepper.cursor.chapter,
      step: stepper.cursor.step,
    });
    return () => {
      delete w.__presentationCursor;
    };
  }, [stepper.cursor.chapter, stepper.cursor.step]);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const audioSrc =
    mode === "manual" || stepText === "" || ended
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => {
    if (ended) return;
    if (atEnd) setEnded(true);
    else stepper.next();
  }, [stepper, atEnd, ended]);

  // 每步时长以 CSS 变量 --sc-step-dur 挂在 .scene 上：规格章的「焦点随口播移动」和 count-up 按它排时间。
  // 有音频就用真实时长（元数据一到就更新），没有就按 3.0 字/秒估（MiniMax 中文音色实测）。
  // 记的是 1× 时长，倍速在下面统一除，这样切倍速不用重探音频。
  const [baseDurMs, setBaseDurMs] = useState(() => Math.max(1500, stepText.length * 333));
  useEffect(() => {
    let alive = true;
    setBaseDurMs(Math.max(1500, stepText.length * 333));
    if (!audioSrc) return;
    const probe = new Audio();
    probe.preload = "metadata";
    probe.onloadedmetadata = () => { if (alive && Number.isFinite(probe.duration) && probe.duration > 0) setBaseDurMs(Math.round(probe.duration * 1000)); };
    probe.src = audioSrc;
    return () => { alive = false; probe.onloadedmetadata = null; probe.src = ""; };
  }, [audioSrc, stepText]);
  // 倍速只作用于有声模式；manual 下没有时间轴可言，保持 1× 的节奏。
  const effRate = mode === "manual" ? 1 : rate;
  const stepDurMs = Math.round(baseDurMs / effRate);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
    paused,
    rate: effRate,
  });

  // What a click on the stage means depends on who's driving the timeline.
  // In manual / audio the viewer is, so a click advances. In auto the page
  // is, so a click holds it — advancing by click there would fight the
  // audio that's still playing. (Arrow keys still step in every mode, which
  // is how you scrub while paused.)
  const onStageClick = useCallback(() => {
    if (mode === "auto" && autoStarted) togglePause();
    else if (ended) return;
    else if (atEnd) setEnded(true);
    else stepper.next();
  }, [mode, autoStarted, togglePause, stepper, atEnd, ended]);

  return (
    <>
      <Stage onStageClick={onStageClick}>
        {ended ? (
          <EndCredits credits={CREDITS} />
        ) : (
          <div key={ch.id} className="scene" style={{ "--sc-step-dur": `${stepDurMs}ms` } as React.CSSProperties}>
            <Cmp step={stepper.cursor.step} />
          </div>
        )}
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} rate={rate} onRate={setRate} />
      <PausedIndicator visible={mode === "auto" && autoStarted && paused} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
      {layoutDebugOn && <LayoutDebug />}
    </>
  );
}
